"""Table added

Revision ID: 04d03b3e96d9
Revises: 07e01e8880f8
Create Date: 2022-12-12 17:36:07.308499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04d03b3e96d9"
down_revision = "07e01e8880f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
