"""Table added

Revision ID: 07e01e8880f8
Revises: ddbadc3ca2fd
Create Date: 2022-12-12 17:33:37.999779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07e01e8880f8"
down_revision = "ddbadc3ca2fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
