"""Table added

Revision ID: 1af75904fbef
Revises: ab4501c47607
Create Date: 2022-12-12 17:58:02.232446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1af75904fbef"
down_revision = "ab4501c47607"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
