"""Table added

Revision ID: 39710e75923d
Revises: 15408814a32e
Create Date: 2022-12-12 16:10:55.422368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "39710e75923d"
down_revision = "15408814a32e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("competition", sa.Column("created_by", sa.TIMESTAMP(), nullable=True))
    op.add_column("competition", sa.Column("updated_by", sa.TIMESTAMP(), nullable=True))
    op.add_column("entry", sa.Column("created_by", sa.TIMESTAMP(), nullable=True))
    op.add_column("entry", sa.Column("updated_by", sa.TIMESTAMP(), nullable=True))
    op.add_column("user", sa.Column("created_by", sa.TIMESTAMP(), nullable=True))
    op.add_column("user", sa.Column("updated_by", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_by")
    op.drop_column("user", "created_by")
    op.drop_column("entry", "updated_by")
    op.drop_column("entry", "created_by")
    op.drop_column("competition", "updated_by")
    op.drop_column("competition", "created_by")
    # ### end Alembic commands ###
