"""Table added

Revision ID: 54b7360ee4a2
Revises: 04d03b3e96d9
Create Date: 2022-12-12 17:39:06.061093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b7360ee4a2'
down_revision = '04d03b3e96d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
