"""Table added

Revision ID: 8ebef8361081
Revises: 39710e75923d
Create Date: 2022-12-12 16:15:48.051034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ebef8361081"
down_revision = "39710e75923d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
