"""Table added

Revision ID: ab4501c47607
Revises: 54b7360ee4a2
Create Date: 2022-12-12 17:55:21.120033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab4501c47607"
down_revision = "54b7360ee4a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
