"""Table added

Revision ID: ddbadc3ca2fd
Revises: 8ebef8361081
Create Date: 2022-12-12 17:26:38.152084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddbadc3ca2fd"
down_revision = "8ebef8361081"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
